// Generated by CoffeeScript 1.3.3
(function() {
  var P, Twitter;

  Twitter = require('immortal-ntwitter');

  P = require("daizoru-toolbox").P;

  module.exports = (function() {

    function exports(config) {
      this.config = config;
      this.twitter = new Twitter(this.config);
    }

    exports.prototype.start = function() {
      var _this = this;
      return this.twitter.immortalStream('statuses/sample', null, function(s) {
        s.on('error', function(err) {
          return _this.error(err);
        });
        return s.on('data', function(tweet) {
          if (tweet.text.length > 40) {
            return;
          }
          if (P(0.9)) {
            return;
          }
          return _this.emit(tweet.text);
        });
      });
    };

    return exports;

  })();

}).call(this);
